language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.4
  - DJANGO_VERSION=1.6
install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script: make test
